server:
  port: 8083

spring:
  application:
    name: SqlResultSetMapping
  jpa:
    databse: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/sql_result_set_mapping
    username: postgres
    password: root
  database:
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'